name: lockdin-school
services:
  intelligence-service:
    build: .
    container_name: intelligence-service
    expose:
      - "8080"
    env_file:
      - .env.local
    networks:
      - lockdin-network
      - inten-sn
    depends_on:
      - intelligenceDB

  intelligenceDB:
    container_name: intelligence-db
    image: postgres:16-alpine
    command: -p 5436
    ports:
      - "5436:5436"
    env_file:
      - .env.local
    networks:
      - inten-sn
    volumes:
      - type: volume
        source: intelligence-storage
        target: /var/lib/postgresql/intelligence/data


volumes:
  intelligence-storage:

networks:
  inten-sn: