use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use sqlx::FromRow;
use uuid::Uuid;

/// Full row as read from `progress_history`.
#[derive(Debug, Clone, FromRow)]
pub struct ProgressHistoryRow {
    pub id: i64,
    pub student_id: Uuid,
    pub concept_id: Uuid,
    pub observation_id: Uuid, // the traceability link back to the raw Observation
    pub questions_answered: i32,
    pub questions_correct: i32,
    pub accuracy: Decimal, // Postgres-generated
    pub created_at: DateTime<Utc>,
}

/// What ProgressService needs to provide to append a `progress_history` row.
/// No `id`, `accuracy`, or `created_at` — all generated by Postgres.
#[derive(Debug, Clone)]
pub struct NewProgressHistory {
    pub student_id: Uuid,
    pub concept_id: Uuid,
    pub observation_id: Uuid,
    pub questions_answered: i32,
    pub questions_correct: i32,
}
